export const skillsData = [
    'Python',
    'Machine Learning',
    'Deep Learning',
    'Data Analysis',
    'Scikit-Learn',
    'Seaborn',
    'Matplotlib',
    'Django',
    'Flask',
    'HTML',
    'CSS',
    'Javascript',
    'Typescript',
    'React',
    'Tailwind',
    'MongoDB',
    'MySQL',  
    'Bootstrap',
  ]